package com.mossle.xiangmu.persistence.domain;

// Generated by Hibernate Tools
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TravelInfo .
 *
 * @author Lingo
 */
@Entity
@Table(name = "zi_jin")
public class zijin implements java.io.Serializable {
    private static final long serialVersionUID = 0L;

    /** null. */
    private Long id;

    /** null. */
    private String name;



    /** null. */
    private String gongys;

    /** null. */
    private String zongjine;

    /** null. */
    private String yifuyie;





    /** null. */
    private String namej;



    public zijin() {
    }

    public zijin(Long id) {
        this.id = id;
    }

    public zijin(Long id, String name,  String gongys,
                      String zongjine, String yifuyie ) {
        this.id = id;
        this.name = name;

        this.gongys = gongys;
        this.zongjine = zongjine;
        this.yifuyie = yifuyie;

        this.namej = namej;

    }

    /** @return null. */
    @Id
    @Column(name = "id", unique = true, nullable = false)
    public Long getId() {
        return this.id;
    }

    /**
     * @param id
     *            null.
     */
    public void setId(Long id) {
        this.id = id;
    }

    /** @return null. */
    @Column(name = "name", length = 200)
    public String getName() {
        return this.name;
    }

    /**
     * @param name
     *            null.
     */
    public void setName(String name) {
        this.name = name;
    }

    /** @return null. */


    /**
     * @param
     *


    /** @return null. */
    @Column(name = "gongys", length = 50)
    public String getgongys() {
        return this.gongys;
    }

    /**
     * @param
     *
     */
    public void setgongys(String gongys) {
        this.gongys = gongys;
    }

    /** @return null. */
    @Column(name = "zongjine", length = 50)
    public String getzongjine() {
        return this.zongjine;
    }

    /**
     * @param
     *
     */
    public void setzongjine(String zongjine) {
        this.zongjine = zongjine;
    }

    /** @return null. */
    @Column(name = "yifuyie", length = 100)
    public String getyifuyie() {
        return this.yifuyie;
    }

    /**
     * @param
     *
     */
    public void setyifuyie(String yifuyie) {
        this.yifuyie = yifuyie;
    }





    /** @return null. */
    @Column(name = "namej", length = 64)
    public String getnamej() {
        return this.namej;
    }

    /**
     * @param
     *
     */
    public void setnamej(String namej) {
        this.namej = namej;
    }


}
